version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=reactupskill
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=example
      - TYPEORM_PASSWORD=example
      - TYPEORM_DATABASE=slusarskie
