version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - SEED_N=${DB_SEED_INVOICES}
      - API_PORT=4000
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=${DB_USER}
      - TYPEORM_PASSWORD=${DB_PASSWORD}
      - TYPEORM_DATABASE=${DB_NAME}
